# Generated by Django 5.1.1 on 2025-06-11 00:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ECG',
            fields=[
                ('id_ecg', models.AutoField(primary_key=True, serialize=False)),
                ('archivo_ecg', models.FileField(upload_to='archivo_ecg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'csv'])])),
                ('fecha_informe', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField()),
                ('homoclave', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('tipo_archivo', models.CharField(choices=[('ECG', 'Electrocardiograma Digital'), ('TAC', 'Tacograma')], default='ECG', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisDominioTiempo',
            fields=[
                ('id_analisis_tiempo', models.AutoField(primary_key=True, serialize=False)),
                ('nni_mean', models.FloatField()),
                ('nni_min', models.FloatField()),
                ('nni_max', models.FloatField()),
                ('hr_mean', models.FloatField()),
                ('hr_min', models.FloatField()),
                ('hr_max', models.FloatField()),
                ('std_hr', models.FloatField()),
                ('nni_diff_mean', models.FloatField()),
                ('nni_diff_min', models.FloatField()),
                ('nni_diff_max', models.FloatField()),
                ('sdnn', models.FloatField()),
                ('sdnn_index', models.FloatField()),
                ('sdann', models.FloatField()),
                ('rmssd', models.FloatField()),
                ('sdsd', models.FloatField()),
                ('nn50', models.FloatField()),
                ('pnn50', models.FloatField()),
                ('nn20', models.FloatField()),
                ('rr_mean', models.FloatField()),
                ('tinn_n', models.FloatField(default=0.0)),
                ('tinn_m', models.FloatField(default=0.0)),
                ('tinn', models.FloatField(default=0.0)),
                ('tri_index', models.FloatField(default=0.0)),
                ('total_intervalos_rr', models.IntegerField()),
                ('ecg', models.OneToOneField(db_column='ID_ECG', on_delete=django.db.models.deletion.CASCADE, to='paciente.ecg')),
            ],
            options={
                'db_table': 'analisis_dominio_tiempo',
            },
        ),
        migrations.CreateModel(
            name='AnalisisDominioFrecuencia',
            fields=[
                ('id_analisis_frecuencia', models.AutoField(primary_key=True, serialize=False)),
                ('potencia_vlf', models.FloatField(default=0.0)),
                ('pico_vlf', models.FloatField(default=0.0)),
                ('potencia_vlf_log', models.FloatField(default=0.0)),
                ('porcentaje_vlf', models.FloatField(default=0.0)),
                ('potencia_lf', models.FloatField(default=0.0)),
                ('pico_lf', models.FloatField(default=0.0)),
                ('potencia_lf_log', models.FloatField(default=0.0)),
                ('porcentaje_lf', models.FloatField(default=0.0)),
                ('potencia_hf', models.FloatField(default=0.0)),
                ('pico_hf', models.FloatField(default=0.0)),
                ('potencia_hf_log', models.FloatField()),
                ('porcentaje_hf', models.FloatField(default=0.0)),
                ('potencia_total', models.FloatField(default=0.0)),
                ('potencia_lf_nu', models.FloatField(default=0.0)),
                ('potencia_hf_nu', models.FloatField(default=0.0)),
                ('lf_hf_ratio', models.FloatField(default=0.0)),
                ('ecg', models.ForeignKey(db_column='ID_ECG', on_delete=django.db.models.deletion.CASCADE, to='paciente.ecg')),
            ],
            options={
                'db_table': 'analisis_dominio_frecuencia',
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id_especialista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialista', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, verbose_name='Fecha Nacimiento')),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(blank=True, max_length=45, verbose_name='Nombre del paciente')),
                ('apellido_paterno', models.CharField(blank=True, max_length=45, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=45, verbose_name='Apellido materno')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('correo', models.CharField(blank=True, max_length=45, verbose_name='Correo electrónico')),
                ('sexo', models.CharField(blank=True, max_length=15, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('imc', models.FloatField(blank=True, null=True, verbose_name='Indice de masa corporal')),
                ('uso_de_medicamentos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Medicamentos')),
                ('actividad_fisica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Actividad física')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='paciente.especialista')),
            ],
        ),
        migrations.AddField(
            model_name='ecg',
            name='paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
